// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpDoc_Manager.Data;

#nullable disable

namespace OpDoc_Manager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpDoc_Manager.Model.Entity.Forklift", b =>
                {
                    b.Property<string>("UniqueId")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.ToTable("Forklifts");
                });

            modelBuilder.Entity("OpDoc_Manager.Model.Entity.Forklift", b =>
                {
                    b.OwnsOne("OpDoc_Manager.Model.Entity.Forklift+GeneralInformation", "General", b1 =>
                        {
                            b1.Property<string>("ForkliftUniqueId")
                                .HasColumnType("text");

                            b1.Property<int>("ControlMethod")
                                .HasColumnType("integer");

                            b1.Property<int>("EnergySource")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("EntryIntoService")
                                .HasColumnType("date");

                            b1.Property<int>("ForkliftType")
                                .HasColumnType("integer");

                            b1.Property<string>("Manufacturer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("ManufacturingYear")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ProductionNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ForkliftUniqueId");

                            b1.ToTable("Forklifts");

                            b1.WithOwner()
                                .HasForeignKey("ForkliftUniqueId");
                        });

                    b.Navigation("General")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
